Completed Update and editing as well as completed validations
fcodelabs/training-ramp-up pull request #320
Opened 2023-07-28 05:12 UTC by AbdullahMarikkar

[ITP-1867]

2023-07-28 05:15 UTC, shamal-iroshan commented on front-end/src/Components/GridTable/RestrictedDatePicker.tsx
> +            // eslint-disable-next-line @typescript-eslint/no-explicit-any
don't disable the lint rules, fix the issue

2023-07-28 05:15 UTC, shamal-iroshan requested changes
fix issue

2023-07-28 06:03 UTC, AbdullahMarikkar commented
Fixed the Issue

2023-08-02 06:05 UTC, shamal-iroshan approved these changes

2023-08-02 06:05 UTC, merged