Sprint Review Changes
fcodelabs/training-ramp-up pull request #382
Opened 2023-08-31 18:13 UTC by PAMUDIABEYKOON

2023-09-01 07:09 UTC, JinapriyaM approved these changes

2023-09-01 07:32 UTC, shamal-iroshan commented on front-end/src/App.tsx
> +          <Route path="/main" element={<Main />} />
can store these paths in a constant file

2023-09-01 07:33 UTC, shamal-iroshan commented on front-end/src/api/authApi.tsx
> +    console.log(response.data.message);
remove unwanted logs

2023-09-01 07:37 UTC, shamal-iroshan commented on front-end/src/components/NavigationBar/NavigationBar.tsx
> +    localStorage.removeItem('token');
don't store tokens in local storage

2023-09-01 07:41 UTC, shamal-iroshan commented on front-end/src/redux/saga.tsx
> +  yield takeLatest(getAllStudents.type, getAllStudentsSaga);
can directly listen to the action, no need to get the type

2023-09-01 07:43 UTC, shamal-iroshan requested changes
fix commented things

2023-09-07 02:36 UTC, shamal-iroshan approved these changes

2023-09-07 02:36 UTC, merged