Web create grid with crud
fcodelabs/training-ramp-up pull request #413
Opened 2023-10-10 06:40 UTC by NimeshPiyumantha

[ITP-2320] [ITP-2323] [ITP-2313]

2023-10-13 06:52 UTC, shamal-iroshan commented on web-front_end/src/index.tsx
> +/* eslint-disable react/react-in-jsx-scope */
don't disable lint rules

2023-10-13 06:55 UTC, shamal-iroshan requested changes
fix lint issue

2023-10-13 07:03 UTC, NimeshPiyumantha commented
Done

2023-10-25 06:33 UTC, shamal-iroshan approved these changes

2023-10-25 06:33 UTC, merged